name: ${project.artifactId}
main: com.chaseoes.firstjoinplus.FirstJoinPlus
version: ${project.version}
description: ${project.description}
author: chaseoes
dev-url: http://dev.bukkit.org/server-mods/${plugin.name.lower}/
website: http://dev.bukkit.org/server-mods/${plugin.name.lower}/
softdepend: [GeoIPTools]
commands:
  firstjoinplus:
    description: ${project.name} command(s).
    aliases: fjp
    usage: /firstjoinplus [reload|setspawn|debug]
permissions:
  firstjoinplus.reload:
    description: Permission to use the /${plugin.name.lower} reload command.
  firstjoinplus.setspawn:
    description: Permission to use the /${plugin.name.lower} setspawn command.
  firstjoinplus.debug:
    description: Permission to use the /${plugin.name.lower} debug command.
  firstoinplus.exempt:
    description: Exempts user from FJP.